version: '2'
services:
  nginx:
    build: nginx/
  django:
    build: django/
    ports:
      - "80:9000"
    depends_on:
      - nginx
  gunicorn:
    build: gunicorn/
    depends_on:
      - django
